import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/ThemeProvider";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ThemeProvider attribute="class" defaultTheme="system">
            <div className="min-h-screen">
              <Navbar />
              <main className="py-6">
                {/*container to center content */}
                <div className="max-w-6xl mx-auto px-4">
                  <div className="grid grid-cols-1 lg:grid-cols-4 gap-5">
                    {/* Sidebar - 1/4 width on desktop */}
                    <div className="hidden lg:block lg:col-span-1">
                      <Sidebar />
                    </div>
                    {/* Main content - 3/4 width on desktop */}
                    <div className="lg:col-span-3">{children}</div>
                  </div>
                </div>
              </main>
            </div>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
